<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('series', 'pre', 'boolean', null, array(
            'type' => 'boolean',
            'default' => '0',
        ));

        $this->addColumn('template', 'email_title', 'clob', null, array(
            'type' => 'clob',
        ));

        $this->addColumn('template', 'email_template', 'clob', null, array(
            'type' => 'clob',
        ));

        $this->addColumn('template', 'email_filename', 'clob', null, array(
            'type' => 'clob',
        ));
    }

    public function down()
    {
        $this->removeColumn('series', 'pre');
        $this->removeColumn('template', 'email_template');
        $this->removeColumn('template', 'email_title');
    }
}