<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('unit', array(
            'id' =>
                array(
                    'type' => 'integer',
                    'length' => '8',
                    'autoincrement' => '1',
                    'primary' => '1',
                ),
            'name' =>
                array(
                    'type' => 'string',
                    'length' => '50',
                ),
        ), array(
            'primary' =>
                array(
                    0 => 'id',
                ),
            'charset' => 'utf8',
        ));
        $this->addColumn('item', 'unit', 'string', '50', array());
    }

    public function down()
    {
        $this->dropTable('unit');
        $this->removeColumn('item', 'unit');
    }
}